version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    command: yarn start:dev
    depends_on:
      - postgres
    profiles:
      - development
      - production
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
  test:
    build:
      context: ./
      dockerfile: Dockerfile
    command: yarn test
    depends_on:
      - postgres
    profiles:
      - tests
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    profiles:
      - development
      - tests
      - production
  pgweb:
    container_name: pgweb
    restart: always
    image: sosedoff/pgweb
    ports:
      - "8081:8081"
    links:
      - postgres:postgres
    environment:
      - DATABASE_URL=postgres://myuser:mypassword@postgres:5432/mydatabase?sslmode=disable
    depends_on:
      - postgres
    profiles:
      - development
  validator-api:
    image: pavelrozhkov/wrapper:6.3.11
    ports:
      - "3500:3500"
    environment:
      SESSION_CACHE_DURATION: -1
    profiles:
      - development
      - tests
      - production

volumes:
  postgres_data:
