version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    command: yarn start:dev
    depends_on:
      - postgres
    profiles:
      - development
      - production
    env_file:
      - ./envs/.env.development
  test:
    build:
      context: ./
      dockerfile: Dockerfile
    command: yarn test
    depends_on:
      - postgres
    profiles:
      - tests
    env_file:
      - ./envs/.env.test
  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    profiles:
      - development
      - tests
      - production
  validator-api:
    image: pavelrozhkov/wrapper:6.3.11
    ports:
      - "3500:3500"
    environment:
      SESSION_CACHE_DURATION: -1
    profiles:
      - development
      - tests
      - production

volumes:
  postgres_data:
